import type { SubjectKey } from './subject'

export type SubjectTopicsMap = Record<SubjectKey, string[]>

export const SUBJECT_KEY_TO_TOPICS: SubjectTopicsMap = {
  anatomy: [
    'General Anatomy',
    'Embryology',
    'Histology',
    'Genetics',
    'Upper Limb',
    'Lower Limb',
    'Thorax',
    'Abdomen',
    'Pelvis & Perineum',
    'Head & Neck',
    'Neuroanatomy',
    'Surface Anatomy',
    'Radiological Anatomy',
  ],
  physiology: [
    'General Physiology',
    'Cell Physiology',
    'Blood',
    'Nerve & Muscle',
    'Cardiovascular System',
    'Respiratory System',
    'Gastrointestinal System',
    'Renal Physiology',
    'Endocrinology',
    'Reproductive Physiology',
    'Central Nervous System',
    'Special Senses',
    'Acid-Base Balance',
    'Temperature Regulation',
  ],
  biochemistry: [
    'Biomolecules',
    'Enzymes',
    'Vitamins',
    'Nutrition',
    'Bioenergetics',
    'Carbohydrate Metabolism',
    'Lipid Metabolism',
    'Protein Metabolism',
    'Nucleotide Metabolism',
    'Molecular Biology',
    'DNA Replication',
    'Transcription',
    'Translation',
    'Gene Regulation',
    'Cancer Biochemistry',
    'Clinical Biochemistry',
  ],
  pathology: [
    'Cell Injury',
    'Inflammation',
    'Healing',
    'Hemodynamic Disorders',
    'Neoplasia',
    'Genetic Disorders',
    'Immunopathology',
    'Environmental Pathology',
    'Hematology',
    'Cardiovascular Pathology',
    'Respiratory Pathology',
    'Gastrointestinal Pathology',
    'Liver & Biliary Pathology',
    'Renal Pathology',
    'Endocrine Pathology',
    'Breast',
    'Female Genital Tract',
    'Male Genital Tract',
    'Bone & Soft Tissue',
    'Skin',
    'CNS',
    'Cytology',
  ],
  pharmacology: [
    'General Pharmacology',
    'Autonomic Nervous System',
    'Cardiovascular Drugs',
    'Central Nervous System Drugs',
    'Respiratory Drugs',
    'Gastrointestinal Drugs',
    'Endocrine Drugs',
    'NSAIDs',
    'Chemotherapy',
    'Antibiotics',
    'Antifungals',
    'Antivirals',
    'Antitubercular Drugs',
    'Antimalarials',
    'Anticancer Drugs',
    'Clinical Pharmacology',
    'Toxicology',
  ],
  microbiology: [
    'Immunology',
    'Bacteriology',
    'Virology',
    'Mycology',
    'Parasitology',
    'Sterilization & Disinfection',
    'Hospital Infection',
    'Vaccines',
    'Laboratory Diagnosis',
  ],
  forensic_medicine: [
    'Medical Jurisprudence',
    'Identification',
    'Thanatology',
    'Mechanical Injuries',
    'Thermal Injuries',
    'Poisoning',
    'Sexual Offences',
    'Forensic Psychiatry',
    'Autopsy',
  ],
  community_medicine: [
    'Epidemiology',
    'Biostatistics',
    'Screening',
    'Demography',
    'Nutrition',
    'Environment',
    'Occupational Health',
    'National Health Programmes',
    'Vaccination',
    'Maternal & Child Health',
    'Health Management',
    'International Health',
  ],
  general_medicine: [
    'Cardiology',
    'Respiratory Medicine',
    'Gastroenterology',
    'Nephrology',
    'Neurology',
    'Endocrinology',
    'Rheumatology',
    'Hematology',
    'Infectious Diseases',
    'Critical Care',
    'Toxicology',
    'ECG',
    'Electrolytes',
    'Acid-Base Disorders',
  ],
  dermatology: [
    'Skin Anatomy',
    'Leprosy',
    'Sexually Transmitted Diseases',
    'Bacterial Diseases',
    'Viral Diseases',
    'Fungal Diseases',
    'Autoimmune Disorders',
    'Pigmentary Disorders',
    'Vesiculobullous Disorders',
    'Skin Tumours',
  ],
  psychiatry: [
    'Schizophrenia',
    'Mood Disorders',
    'Anxiety Disorders',
    'OCD',
    'Personality Disorders',
    'Substance Abuse',
    'Child Psychiatry',
    'Sleep Disorders',
    'Psychopharmacology',
  ],
  general_surgery: [
    'General Surgery',
    'Trauma',
    'Shock',
    'Burns',
    'Wound Healing',
    'Thyroid',
    'Breast',
    'Gastrointestinal Surgery',
    'Hepatobiliary Surgery',
    'Pancreatic Surgery',
    'Vascular Surgery',
    'Urology',
    'Neurosurgery',
    'Plastic Surgery',
  ],
  orthopedics: [
    'Fractures',
    'Bone Tumours',
    'Osteomyelitis',
    'Arthritis',
    'Spine',
    'Sports Injuries',
    'Metabolic Bone Disease',
    'Pediatric Orthopaedics',
  ],
  anesthesiology: [
    'General Anaesthesia',
    'Local Anaesthesia',
    'Airway Management',
    'Ventilation',
    'Monitoring',
    'ICU',
    'CPR',
    'Pain Management',
  ],
  radiology: [
    'X-Ray',
    'CT',
    'MRI',
    'Ultrasound',
    'Nuclear Medicine',
    'Contrast Media',
    'Radiation Physics',
    'Interventional Radiology',
  ],
  obstetrics_and_gynecology: [
    'Physiology of Pregnancy',
    'Antenatal Care',
    'Labour',
    'High-Risk Pregnancy',
    'Hypertension in Pregnancy',
    'Diabetes in Pregnancy',
    'Postpartum Hemorrhage',
    'Infertility',
    'Contraception',
    'Menstrual Disorders',
    'Gynecologic Oncology',
    'Urogynecology',
  ],
  pediatrics: [
    'Growth & Development',
    'Nutrition',
    'Neonatology',
    'Pediatric Infections',
    'Cardiology',
    'Neurology',
    'Nephrology',
    'Vaccination',
    'Pediatric Emergencies',
  ],
  ophthalmology: [
    'Anatomy',
    'Optics',
    'Glaucoma',
    'Cataract',
    'Retina',
    'Uveitis',
    'Neuro-Ophthalmology',
    'Ocular Trauma',
  ],
  ent: [
    'Ear',
    'Nose',
    'Paranasal Sinuses',
    'Oral Cavity',
    'Pharynx',
    'Larynx',
    'Neck',
    'Audiology',
    'Vestibular Disorders',
  ],
}

/** @deprecated Use SUBJECT_KEY_TO_TOPICS */
export const SUBJECT_TOPICS = SUBJECT_KEY_TO_TOPICS

export interface SubjectTopicGroup {
  subject: SubjectKey
  topics: string[]
}

export function getTopicsForSubjects(
  subjects: SubjectKey[],
): SubjectTopicGroup[] {
  return subjects.map((subject) => ({
    subject,
    topics: SUBJECT_KEY_TO_TOPICS[subject] ?? [],
  }))
}

export function getFlatTopicsForSubjects(subjects: SubjectKey[]): string[] {
  const seen = new Set<string>()
  const result: string[] = []
  for (const subject of subjects) {
    for (const topic of SUBJECT_KEY_TO_TOPICS[subject] ?? []) {
      if (!seen.has(topic)) {
        seen.add(topic)
        result.push(topic)
      }
    }
  }
  return result
}
